name: Deploy Discord LLM Workspace Bot to Mac Mini

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  APP_NAME: discord-llm-workspace
  CONTAINER_NAME: discord-llm-workspace-bot
  PORT: 3003

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure Docker environment
      run: |
        echo "Setting up Docker environment for Discord LLM Workspace Bot..."
        
        # Create Docker config directory
        mkdir -p ~/.docker
        
        # Create config without keychain
        cat > ~/.docker/config.json << 'EOF'
        {
          "auths": {},
          "credsStore": "",
          "credHelpers": {},
          "experimental": "disabled"
        }
        EOF
        
        # Ensure shared network exists
        docker network create gibbs-apps 2>/dev/null || echo "Network already exists"
        
        # Test Docker access
        echo "Testing Docker access..."
        docker --version
        
    - name: Set up deployment directory
      run: |
        DEPLOY_DIR=~/deployments/${{ env.APP_NAME }}
        echo "Cleaning up old deployment..."
        
        # Stop any existing containers
        docker stop ${{ env.CONTAINER_NAME }} 2>/dev/null || true
        docker rm ${{ env.CONTAINER_NAME }} 2>/dev/null || true
        
        # Clean up directory but preserve data volumes
        rm -rf $DEPLOY_DIR
        mkdir -p $DEPLOY_DIR
        mkdir -p $DEPLOY_DIR/logs
        mkdir -p $DEPLOY_DIR/data
        mkdir -p $DEPLOY_DIR/backups
        
        echo "Copying new code..."
        cp -r $GITHUB_WORKSPACE/* $DEPLOY_DIR/
        
    - name: Copy secrets
      run: |
        DEPLOY_DIR=~/deployments/${{ env.APP_NAME }}
        APP_SECRETS=~/secrets/${{ env.APP_NAME }}
        
        echo "Copying environment file..."
        if [ -f "$APP_SECRETS/production.env" ]; then
          cp $APP_SECRETS/production.env $DEPLOY_DIR/.env
          echo "✅ Environment file copied as .env"
        else
          echo "❌ Environment file not found at $APP_SECRETS/production.env"
          exit 1
        fi
        
    - name: Run database migration
      run: |
        cd ~/deployments/${{ env.APP_NAME }}
        echo "Running database migration..."
        
        # Install dependencies for migration
        npm ci
        
        # Run migration script
        npm run migrate
        
        echo "✅ Database migration completed"
        
    - name: Build and start container
      env:
        DOCKER_CONFIG: ~/.docker
        DOCKER_BUILDKIT: 0
      run: |
        cd ~/deployments/${{ env.APP_NAME }}
        echo "Building Discord LLM Workspace Bot..."
        
        # Stop any existing container
        docker stop ${{ env.CONTAINER_NAME }} 2>/dev/null || true
        docker rm ${{ env.CONTAINER_NAME }} 2>/dev/null || true
        
        # Build the image
        docker build --no-cache -t discord-llm-workspace:latest .
        
        # Run the container with shared network
        docker run -d \
          --name ${{ env.CONTAINER_NAME }} \
          --restart unless-stopped \
          --network gibbs-apps \
          -p ${{ env.PORT }}:${{ env.PORT }} \
          -v $(pwd)/logs:/usr/src/app/logs:rw \
          -v $(pwd)/data:/usr/src/app/data:rw \
          -v $(pwd)/backups:/usr/src/app/backups:rw \
          --env-file .env \
          -e NODE_ENV=production \
          -e PORT=${{ env.PORT }} \
          discord-llm-workspace:latest
        
    - name: Verify deployment
      run: |
        echo "Waiting for container to start..."
        sleep 30
        
        echo "Checking container status..."
        docker ps | grep ${{ env.CONTAINER_NAME }}
        
        echo "Running health check..."
        cd ~/deployments/${{ env.APP_NAME }}
        
        # Wait a bit more for full initialization
        sleep 15
        
        # Use the built-in health check from the bot
        if docker exec ${{ env.CONTAINER_NAME }} npm run test:health; then
          echo "✅ Discord LLM Workspace Bot deployment successful!"
        else
          echo "❌ Health check failed"
          echo "Container logs:"
          docker logs --tail=50 ${{ env.CONTAINER_NAME }}
          exit 1
        fi
        
        # Check Discord connection
        echo "Checking Discord connection..."
        sleep 5
        if docker logs ${{ env.CONTAINER_NAME }} | grep -E "(online and ready|started successfully)"; then
          echo "✅ Discord connected successfully"
        else
          echo "⚠️ Discord connection status unclear, checking logs..."
          docker logs --tail=20 ${{ env.CONTAINER_NAME }}
        fi
        
    - name: Test admin commands
      run: |
        echo "Testing admin command system..."
        cd ~/deployments/${{ env.APP_NAME }}
        
        # Test admin command service initialization
        if docker logs ${{ env.CONTAINER_NAME }} | grep -E "(slash commands|admin command|Successfully reloaded)"; then
          echo "✅ Admin commands initialized"
        else
          echo "⚠️ Admin command status unclear"
        fi
        
        # Test MongoDB connection
        if docker logs ${{ env.CONTAINER_NAME }} | grep -E "(Memory service connected|technical workspace)"; then
          echo "✅ MongoDB connected with technical workspace"
        else
          echo "⚠️ MongoDB connection status unclear"
        fi
        
    - name: Clean up old images
      run: |
        docker image prune -f --filter label=app=discord-llm-workspace || true
        
    - name: Show final status
      run: |
        echo "=== Discord LLM Workspace Bot Status ==="
        docker ps | grep ${{ env.CONTAINER_NAME }}
        echo ""
        echo "Bot is running on port ${{ env.PORT }}"
        echo "  - Health Check: npm run test:health"
        echo "  - Integration Tests: npm test"
        echo "  - Admin Commands: 13 slash commands available"
        echo "  - Channels: coding, general, projects, planning, analysis, admin"
        echo "  - Memory System: Technical pattern recognition enabled"
        echo "  - Database: MongoDB with technical_workspace collections"
        echo ""
        echo "Network: gibbs-apps"
        docker network inspect gibbs-apps --format='{{range .Containers}}{{.Name}}: {{.IPv4Address}}{{"\n"}}{{end}}'
        echo ""
        echo "Recent logs:"
        docker logs --tail=10 ${{ env.CONTAINER_NAME }}